build:
  stage: build
  variables:
    # https://github.com/GoogleContainerTools/kaniko/issues/3328#issuecomment-2420411160
    GOOGLE_APPLICATION_CREDENTIALS: "/dev/null"
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
     - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH