spring:
  datasource:
    url: 'jdbc:postgresql://db:5432/hapi'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false

hapi:
  fhir:
    implementationguides:
      ph_core:
        name: example.fhir.ph.core
        version: 0.1.0
        reloadExisting: false
        installMode: STORE_AND_INSTALL
        packageUrl: https://build.fhir.org/ig/UP-Manila-SILab/ph-core/package.tgz
        fetchDependencies: true
        dependencyExcludes:
           - "hl7.fhir.uv.extensions"
           - "hl7.terminology.r5"
    logical_urls:
      - http://terminology.hl7.org/*
      - https://terminology.hl7.org/*
      - http://snomed.info/*
      - https://snomed.info/*
      - http://unitsofmeasure.org/*
      - https://unitsofmeasure.org/*
      - http://loinc.org/*
      - https://loinc.org/*
    remote_terminology_service:
      all:
        system: '*'
        url: 'https://tx.fhirlab.net/fhir'